export const webPaths = [
	{
		title: 'home',
		href: '/',
		icon: 'home',
		navPos: 'top',
		enabled: true,
		external: false,
		permissions: [],
		customs: {},
		children: [],
	},
	{
		title: 'settings',
		href: '/settings',
		icon: 'settings',
		navPos: 'top',
		enabled: true,
		external: false,
		permissions: [],
		customs: {},
		children: [],
	},
	{
		title: 'macros',
		href: '/macros',
		icon: 'quickreply',
		navPos: 'top',
		enabled: true,
		external: false,
		permissions: [],
		customs: {},
		children: [],
	},
	{
		title: 'info',
		href: '/info',
		icon: 'info',
		navPos: 'top',
		enabled: true,
		external: false,
		permissions: [],
		customs: {},
		children: [],
	},
] as const;
